name: Ubuntu Server

on:
  workflow_dispatch:

jobs:
  run-sshx:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Terminal Access
      run: |
        curl -sSf https://sshx.io/get | sh -s run
